apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.97.1
    helm:
      values: |
        mode: daemonset
        nameOverride: "otel-collector"
        image: { repository: otel/opentelemetry-collector-contrib }
        config:
          receivers:
            otlp:
              protocols:
                grpc: { endpoint: 0.0.0.0:4317 }
                http: { endpoint: 0.0.0.0:4318 }
          processors:
            batch: {}
            memory_limiter:
              limit_percentage: 80
              check_interval: 1s
          exporters:
            otlp/tempo:
              endpoint: tempo.monitoring.svc:4317
              tls: { insecure: true }
            prometheus:
              endpoint: 0.0.0.0:8889
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlp/tempo]
              metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [prometheus]
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy: { automated: { prune: true, selfHeal: true } }
