apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yaml

# CI updates these image tags via: kustomize edit set image athena/agent=<ecr>:<sha>
images:
- name: athena/agent
  newName: 339713148266.dkr.ecr.us-east-1.amazonaws.com/athena/agent
  newTag: 7ceadb5db16c
- name: athena/k8s-mcp
  newName: 339713148266.dkr.ecr.us-east-1.amazonaws.com/athena/k8s-mcp
  newTag: 92641c8a51fc-34
- name: athena/loki-mcp
  newName: 339713148266.dkr.ecr.us-east-1.amazonaws.com/athena/loki-mcp
  newTag: 92641c8a51fc-33
- name: athena/prom-mcp
  newName: 339713148266.dkr.ecr.us-east-1.amazonaws.com/athena/prom-mcp
  newTag: b39ca9b68fc1-35
